version: "3"

networks:
  minecraft:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1

services:
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - 2456:1194/udp
    restart: unless-stopped
    volumes:
      - ./openvpn:/etc/openvpn

  infrared:
    container_name: infrared
    image: ghcr.io/haveachin/infrared:latest
    environment:
      INFRARED_CONFIG_PATH: "/configs"
    ports:
      - 25565:25565/tcp
    networks:
      minecraft:
        ipv4_address: 192.168.1.1
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./infrared:/configs

  minecraft_spigot:
    container_name: minecraft_spigot
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MEMORY: "7G"
      TYPE: "SPIGOT"
      VERSION: "1.20.1"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft_spigot:/data
    networks:
      minecraft:
        ipv4_address: 192.168.100.1

  minecraft_spigot_back:
    container_name: minecraft_spigot_back
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MEMORY: "7G"
      TYPE: "SPIGOT"
      VERSION: "1.20.1"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft_spigot_back:/data
    networks:
      minecraft:
        ipv4_address: 192.168.100.2

  valheim:
    container_name: valheim
    image: lloesche/valheim-server
    ports:
      - 2456-2457:2456-2457/udp
    env_file:
      - ./secrets/valheim.env
    environment:
      - SERVER_NAME=box
      - WORLD_NAME=Back
      - SERVER_PUBLIC=0
    restart: unless-stopped
    volumes:
      - ./valheim/config:/config
      - ./valheim/data:/opt/valheim

  zomboid:
    container_name: zomboid
    image: afey/zomboid
    ports:
      - 8766:8766/udp
    env_file:
      - ./secrets/zomboid.env
    environment:
      SERVER_NAME: "box"
    restart: unless-stopped
    volumes:
      - ./zomboid:/server-data
